In [1]:
import numpy as np

In [2]:
help(np.random.beta)

Help on built-in function beta:

beta(...) method of numpy.random.mtrand.RandomState instance
    beta(a, b, size=None)
    
    Draw samples from a Beta distribution.
    
    The Beta distribution is a special case of the Dirichlet distribution,
    and is related to the Gamma distribution.  It has the probability
    distribution function
    
    .. math:: f(x; a,b) = \frac{1}{B(\alpha, \beta)} x^{\alpha - 1}
                                                     (1 - x)^{\beta - 1},
    
    where the normalization, B, is the beta function,
    
    .. math:: B(\alpha, \beta) = \int_0^1 t^{\alpha - 1}
                                 (1 - t)^{\beta - 1} dt.
    
    It is often seen in Bayesian inference and order statistics.
    
    .. note::
        New code should use the ``beta`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    a : float or array_like of floats
        Alpha, positive (>0).


In [2]:
A = np.random.normal(loc=1, scale=1, size=36).reshape((-1, 6))
print(A)

[[ 2.60285487  0.19758579  1.42440911  2.50566926  1.75437968  0.490565  ]
 [ 2.43384263  1.00449719  1.12757354 -0.69932468  1.00276404 -1.07381222]
 [ 1.46398983  0.45109     0.17676775  1.13405381  0.63718671  2.44166196]
 [ 1.88423451  1.37904958  0.45294568  1.99290731  0.5980795   1.01011937]
 [ 1.32707937  0.6480118   0.2204227  -0.28151438  2.1294821   1.3434127 ]
 [ 2.31302054  1.55011254 -0.67080398  2.03489367 -0.4210343   3.02888459]]


In [3]:
print(np.linalg.det(A))

31.69424845537331


In [10]:
%%time
for _ in range(2000):
    print(np.linalg.inv(A))

[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.52568346e-02]
 [ 1.96834683e-01 -2.59118337e-01 -5.37775312e-01  8.53989457e-03
   5.96355125e-01  4.24194180e-02]
 [-2.58773307e-01  1.44444174e-02  8.21950232e-01  1.19784814e-01
  -1.26438649e-01 -2.69276213e-01]]
[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.525

[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.52568346e-02]
 [ 1.96834683e-01 -2.59118337e-01 -5.37775312e-01  8.53989457e-03
   5.96355125e-01  4.24194180e-02]
 [-2.58773307e-01  1.44444174e-02  8.21950232e-01  1.19784814e-01
  -1.26438649e-01 -2.69276213e-01]]
[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.525

[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.52568346e-02]
 [ 1.96834683e-01 -2.59118337e-01 -5.37775312e-01  8.53989457e-03
   5.96355125e-01  4.24194180e-02]
 [-2.58773307e-01  1.44444174e-02  8.21950232e-01  1.19784814e-01
  -1.26438649e-01 -2.69276213e-01]]
[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.525

[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.52568346e-02]
 [ 1.96834683e-01 -2.59118337e-01 -5.37775312e-01  8.53989457e-03
   5.96355125e-01  4.24194180e-02]
 [-2.58773307e-01  1.44444174e-02  8.21950232e-01  1.19784814e-01
  -1.26438649e-01 -2.69276213e-01]]
[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.525

In [9]:
%%time
A_inv = np.linalg.inv(A)
for _ in range(2000):
    print(A_inv)

[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.52568346e-02]
 [ 1.96834683e-01 -2.59118337e-01 -5.37775312e-01  8.53989457e-03
   5.96355125e-01  4.24194180e-02]
 [-2.58773307e-01  1.44444174e-02  8.21950232e-01  1.19784814e-01
  -1.26438649e-01 -2.69276213e-01]]
[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.525

[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.52568346e-02]
 [ 1.96834683e-01 -2.59118337e-01 -5.37775312e-01  8.53989457e-03
   5.96355125e-01  4.24194180e-02]
 [-2.58773307e-01  1.44444174e-02  8.21950232e-01  1.19784814e-01
  -1.26438649e-01 -2.69276213e-01]]
[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.525

[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.52568346e-02]
 [ 1.96834683e-01 -2.59118337e-01 -5.37775312e-01  8.53989457e-03
   5.96355125e-01  4.24194180e-02]
 [-2.58773307e-01  1.44444174e-02  8.21950232e-01  1.19784814e-01
  -1.26438649e-01 -2.69276213e-01]]
[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.525

[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.52568346e-02]
 [ 1.96834683e-01 -2.59118337e-01 -5.37775312e-01  8.53989457e-03
   5.96355125e-01  4.24194180e-02]
 [-2.58773307e-01  1.44444174e-02  8.21950232e-01  1.19784814e-01
  -1.26438649e-01 -2.69276213e-01]]
[[ 4.13248712e-01  2.51670417e-01 -4.34516205e-01 -8.29141250e-01
   2.96538418e-02  6.35929609e-01]
 [-6.48070199e-01  5.95789664e-02  1.73681118e-01  1.17507493e+00
   4.01100063e-02 -4.23596080e-01]
 [-5.74621479e-01  3.55223044e-01  1.81088475e+00  9.66906012e-01
  -7.50550595e-01 -1.23036304e+00]
 [ 2.60426015e-01 -2.89467751e-01 -3.76160160e-01  1.89546988e-01
  -9.00564557e-05  9.525